name: Run Agenda Decoder

on:
  push:
    paths:
      - 'agenda.txt' # Triggers only when you update or upload 'agenda.txt'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-python: '3.10'

    - name: Run Script
      run: python extract.py
